Change Finance::Quote module install from VBS/CMD to Windows Powershell
Gnucash/gnucash-on-windows pull request #66
Opened 2024-07-09 18:32 UTC by ericmoon

Removes VBS and command.exe scripts from extra_dist and replaces with Windows Powershell (note, Windows Powershell, not Powershell, which is different).

Also changes the Inno Setup scripts to have the Start Menu point to the powershell script. 

I was able to test all of the functionality except the install of the Start Menu shortcut as I don't have that build environment setup yet.

2024-07-09 19:27 UTC, jralls requested changes
The merge commit was helpful for pointing out to me that I hadn't pushed the commit to put the AQBanking beta back after the release on Sunday, but we really can't have merges in PRs. Please rebase on `https://github.com/Gnucash/gnucash-on-windows master` and force-push that to here.

2024-07-09 19:27 UTC, jralls commented on extra_dist/install-fq-mods.ps1
> +    if ($perlMajor -eq 5) {
Perl 5.0 was released in 1993 and Perl 6 is Raku. The likelihood of this failing is nil so please remove it.

2024-07-09 19:27 UTC, jralls commented on extra_dist/install-fq-mods.ps1
> +            Write-Host "Please manually install version 5.8 or above of"
Please use `$perlversion` in the string instead of hard-coding "5.8".

2024-07-09 19:59 UTC, jralls commented on inno_setup/gnucash-mingw64.iss
> +Name: "{group}\{cm:IconName_InstallFQ}"; Filename: "powershell.exe -ExecutionPolicy Bypass -File ""{app}\bin\install-fq-mods.ps1"""; WorkingDir: "{app}\bin"; Comment: "{cm:IconComment_InstallFQ}"; Ta
```
Running Inno Setup to create C:\gcdev64\gnucash\releases\gnucash-5.8.setup.exe.
Error on line 49 in C:\gcdev64\gnucash\releases\gnucash.iss: Parameter "Filename" cannot include quotes (")
Compile aborted.
```
Taking out the quotes around `{app}\bin\install-fq-mods.ps1` lets it compile but after installing the package the Install Online Price Retrieval shortcut's target is empty so it doesn't show up in the Start menu.

2024-07-09 20:51 UTC, jralls commented on inno_setup/gnucash-mingw64.iss
> +Name: "{group}\{cm:IconName_InstallFQ}"; Filename: "powershell.exe -ExecutionPolicy Bypass -File ""{app}\bin\install-fq-mods.ps1"""; WorkingDir: "{app}\bin"; Comment: "{cm:IconComment_InstallFQ}"; Ta
This works:
```diff
--- a/inno_setup/gnucash-mingw64.iss
+++ b/inno_setup/gnucash-mingw64.iss
@@ -46,7 +46,7 @@ Name: "{group}\GnuCash"; Filename: "{app}\bin\@PACKAGE@.exe"; WorkingDir: "{code
 Name: "{group}\{cm:IconName_README}"; Filename: "{app}\doc\@PACKAGE@\{cm:IconFilename_README}"; Comment: "{cm:IconComment_README}"; Tasks: menuicon
 Name: "{group}\{cm:IconName_FAQ}"; Filename: "http://wiki.gnucash.org/wiki/FAQ"; Tasks: menuicon
 Name: "{group}\{cm:IconName_Bugzilla}"; Filename: "https://bugs.gnucash.org/enter_bug.cgi?product=GnuCash"; Tasks: menuicon
-Name: "{group}\{cm:IconName_InstallFQ}"; Filename: "powershell.exe -ExecutionPolicy Bypass -File ""{app}\bin\install-fq-mods.ps1"""; WorkingDir: "{app}\bin"; Comment: "{cm:IconComment_InstallFQ}"; Tasks: menuicon
+Name: "{group}\{cm:IconName_InstallFQ}"; Filename: "{syswow64}/WindowsPowershell/v1.0/powershell.exe"; Parameters: "-ExecutionPolicy Bypass -File ""{app}\bin\install-fq-mods.ps1"""; WorkingDir: "{app}\bin"; Comment: "{cm:IconComment_InstallFQ}"; Tasks: menuicon
 Name: "{group}\{cm:IconName_Uninstall}"; Filename: "{uninstallexe}"; Comment: "{cm:IconComment_Uninstall}"; Tasks: menuicon

 Name: "{commondesktop}\GnuCash"; Filename: "{app}\bin\@PACKAGE@.exe"; WorkingDir: "{code:GetDocPath}"; Comment: "{cm:IconComment_GnuCash}"; IconFilename: "{app}\share\@PACKAGE@\pixmaps\gnucash-icon.ico"; Tasks: desktopicon

```

2024-07-10 18:52 UTC, ericmoon commented
Rebased and force-pushed.  It's been a while, so let me know if I screwed anything up.

2024-07-17 04:23 UTC, jralls requested changes

2024-07-17 04:23 UTC, jralls commented on extra_dist/install-fq-mods.ps1
> +    if ($perlMajor -eq 5) {
It's still here.

2024-07-17 04:23 UTC, jralls commented on extra_dist/install-fq-mods.ps1
> +            Write-Host "Please manually install version 5.8 or above of"
Another place for `5.$perlVersion`.

2024-07-17 04:23 UTC, jralls commented on extra_dist/install-fq-mods.ps1
> +    pause
New item, I should have noticed this before.  First it doesn't really make sense to test `ALPHAVANTAGE_API_KEY` in the middle, but more significantly it's not necessary to set the environment variable at all. Users can set a preference in GnuCash if they need Alphavantage, but that need is much less than it was. I'm inclined towards removing this and leaving it for GnuCash to deal with at runtime.

2024-07-23 01:13 UTC, jralls commented
You went a bit far with bumping the perl version, 5.38.2.2 isn't available for 32-bit. I'm testing now but my VM is really slow and it's taking forever. Unfortunately I'll be away from this keyboard for a couple of days so I may not be able to push the merge until Thursday.

2024-07-24 04:28 UTC, merged

2024-07-24 04:29 UTC, jralls commented
Thanks!